[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "soulde-robot-zoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mujoco>=3.10.0",
    "numpy>=1.23",
]

[project.scripts]
mujoco-gui = "soulde_robot_zoo.mujoco_gui:main"
